//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using CommonSaisieHoraires;
using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class TimeEntry
    {
        public int Id { get; set; }
        public System.DateTime TheDate { get; set; }
        public decimal StartTime { get; set; }
        public decimal EndTime { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public decimal SumTime {
            get
            {
                if (EndTime == 0)
                {
                    return StartTime;
                }
                else
                {
                    return SaisieHorairesTools.DecToSexag(
                                SaisieHorairesTools.SexagToDec(EndTime) - 
                                SaisieHorairesTools.SexagToDec(StartTime));
                }
            }
            private set { }
        }
    }
}
