//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaisieHorairesClient.SaisieHorairesServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeEntryDataContract", Namespace="http://schemas.datacontract.org/2004/07/SaisieHorairesService")]
    [System.SerializableAttribute()]
    public partial class TimeEntryDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TheDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TheDate {
            get {
                return this.TheDateField;
            }
            set {
                if ((this.TheDateField.Equals(value) != true)) {
                    this.TheDateField = value;
                    this.RaisePropertyChanged("TheDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaisieHorairesServiceRef.ISaisieHorairesService")]
    public interface ISaisieHorairesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/GetTimeEntry", ReplyAction="http://tempuri.org/ISaisieHorairesService/GetTimeEntryResponse")]
        SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract GetTimeEntry(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/GetTimeEntry", ReplyAction="http://tempuri.org/ISaisieHorairesService/GetTimeEntryResponse")]
        System.Threading.Tasks.Task<SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract> GetTimeEntryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/AddNewTimeEntry", ReplyAction="http://tempuri.org/ISaisieHorairesService/AddNewTimeEntryResponse")]
        void AddNewTimeEntry(System.DateTime ATheDate, decimal AStartTime, decimal AEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/AddNewTimeEntry", ReplyAction="http://tempuri.org/ISaisieHorairesService/AddNewTimeEntryResponse")]
        System.Threading.Tasks.Task AddNewTimeEntryAsync(System.DateTime ATheDate, decimal AStartTime, decimal AEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/TimeEntryExistsForDay", ReplyAction="http://tempuri.org/ISaisieHorairesService/TimeEntryExistsForDayResponse")]
        bool TimeEntryExistsForDay(System.DateTime ATheDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/TimeEntryExistsForDay", ReplyAction="http://tempuri.org/ISaisieHorairesService/TimeEntryExistsForDayResponse")]
        System.Threading.Tasks.Task<bool> TimeEntryExistsForDayAsync(System.DateTime ATheDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/GetEntries", ReplyAction="http://tempuri.org/ISaisieHorairesService/GetEntriesResponse")]
        SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract[] GetEntries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaisieHorairesService/GetEntries", ReplyAction="http://tempuri.org/ISaisieHorairesService/GetEntriesResponse")]
        System.Threading.Tasks.Task<SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract[]> GetEntriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaisieHorairesServiceChannel : SaisieHorairesClient.SaisieHorairesServiceRef.ISaisieHorairesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaisieHorairesServiceClient : System.ServiceModel.ClientBase<SaisieHorairesClient.SaisieHorairesServiceRef.ISaisieHorairesService>, SaisieHorairesClient.SaisieHorairesServiceRef.ISaisieHorairesService {
        
        public SaisieHorairesServiceClient() {
        }
        
        public SaisieHorairesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaisieHorairesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaisieHorairesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaisieHorairesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract GetTimeEntry(int id) {
            return base.Channel.GetTimeEntry(id);
        }
        
        public System.Threading.Tasks.Task<SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract> GetTimeEntryAsync(int id) {
            return base.Channel.GetTimeEntryAsync(id);
        }
        
        public void AddNewTimeEntry(System.DateTime ATheDate, decimal AStartTime, decimal AEndTime) {
            base.Channel.AddNewTimeEntry(ATheDate, AStartTime, AEndTime);
        }
        
        public System.Threading.Tasks.Task AddNewTimeEntryAsync(System.DateTime ATheDate, decimal AStartTime, decimal AEndTime) {
            return base.Channel.AddNewTimeEntryAsync(ATheDate, AStartTime, AEndTime);
        }
        
        public bool TimeEntryExistsForDay(System.DateTime ATheDate) {
            return base.Channel.TimeEntryExistsForDay(ATheDate);
        }
        
        public System.Threading.Tasks.Task<bool> TimeEntryExistsForDayAsync(System.DateTime ATheDate) {
            return base.Channel.TimeEntryExistsForDayAsync(ATheDate);
        }
        
        public SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract[] GetEntries() {
            return base.Channel.GetEntries();
        }
        
        public System.Threading.Tasks.Task<SaisieHorairesClient.SaisieHorairesServiceRef.TimeEntryDataContract[]> GetEntriesAsync() {
            return base.Channel.GetEntriesAsync();
        }
    }
}
