//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Director { get; set; }
        [Display(Name = "Release date"), DataType(DataType.Date)]
        public Nullable<System.DateTime> DateReleased { get; set; }
    }
}
