//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntry
    {
        public int Id { get; set; }
        public string project { get; set; }
        public string prestation { get; set; }
        public string desc { get; set; }
    }
}
